version: 0.2
phases:
  install:
    runtime-versions:
      php: 7.3
      java: corretto11
    commands:
      - echo "in the install phase"
    finally:
      - echo This always runs even if the login command fails 
  pre_build:
    commands:
      #- wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.4.0.2170-linux.zip
      #- unzip sonar-scanner-cli-4.4.0.2170-linux.zip
      #- mv sonar-scanner-4.4.0.2170-linux /opt/sonar-scanner
      #- chmod -R 775 /opt/sonar-scanner
      - echo "stage pre_build completed"
  build:
    commands:
      #- aws securityhub batch-import-findings --findings '[{“SchemaVersion”:“2018-10-08",“Id”:“12345",“ProductArn”:“arn:aws-us-gov:securityhub”,“GeneratorId”:“12455",“AwsAccountId”:“34343242",“Types”:[“Software and Configuration Checks/AWS Security Best Practices”,“CreatedAt”:“2020-05-27T17:05:54.832Z”,“UpdatedAt”:“2020-05-28T17:05:54.832Z”,“Severity”:{“Label”:“LOW”},“Title”:“xss”,“Description”:“xss xss”,“Remediation”:{“Recommendation”:{“Text”:“For directions on PHP AWS Best practices, please click this link”,“Url”:“https://goal.com”}},“SourceUrl”:“https://goal.com”,“Resources”:[{“Id”:“456",“Type”:“CodeBuild”,“Partition”:“aws”, “Region”:“us-west-1"}]}]'
      - aws securityhub batch-import-findings --findings '[{"AwsAccountId":"369737379577","CreatedAt":"2020-05-27T17:05:54.832Z","Description":"Vulnerability in a CloudTrail trail","Severity":{"Label":"LOW"},"Types":["Software and Configuration Checks/Vulnerabilities/CVE"],"GeneratorId":"TestGeneratorId","Id":"Id1","ProductArn":"arn:aws:securityhub:ap-south-1:369737379577:product/369737379577/default","Resources":[{"Id":"456","Partition":"aws","Region":"ap-south-1","Type":"CodeBuild"}],"SchemaVersion":"2018-10-08","Title":"CloudTrail trail vulnerability","UpdatedAt":"2020-06-02T16:05:54.832Z"}]'
      - echo "Finished Building...."
