version: 0.2

phases:
  pre_build:
    commands:
    - echo "Installing truffleHog"
    - which pip3 && pip3 --version
    - which python3 && python3 --version
    - pip3 install 'truffleHog>=2.1.0,<3.0'
  build:
    commands:
    - echo "Build started on $(date)"
    - echo "Scanning with truffleHog..."
    - trufflehog --regex --entropy=False ${SOURCE_REPO_URL} > secret_result.txt
  post_build:
    commands:
    - cat secret_result.txt    
    - echo "Build completed on $(date)"
